### PR TITLE
Add export to javascript

### PR DESCRIPTION
**Pull request by siemiatj**
I thought it'd be cool to have an option of exporting stylesheet to a javascript object. Useful if you're working with HTML5 canvas.

### CODE REVIEW

**Comment by selaux** [comment]
Does it make sense to export the image data itself as well? E.g. base64 encoded?

**Comment by siemiatj** [comment]
I think the use cases are marginal.

**Comment by selaux** [comment]
So, I would accept when code style is fixed...

**Comment by siemiatj** [comment]
I have some tests failing that shouldn't be failing as I haven't touched the internals. I'll look into that tomorrow.

screen shot 2017-02-22 at 1 54 12 am

**Pull request merged**
